feat(install): Improves at install script (#30)
- Become executable
- Improves to install 1password for linux
- improve at mesage banners
- bump asdf-vm to 0.16.2 (written in Go)

diff --git a/install b/install
--- a/install
+++ b/install
@@ -27,23 +27,78 @@ esac
 
 echo "Starting dotfiles installer..."
 echo "+----------------------------------------------------------+"
-echo "| PLATFORM_ARCH=$PLATFORM_ARCH; OS=$PLATFORM_OS |"
+echo "| PLATFORM_ARCH=$PLATFORM_ARCH; OS=$PLATFORM_OS;ARCH=$MACHINE_ARCH |"
 echo "+----------------------------------------------------------+"
+
+
+function ensure_1p() {
+  echo "+----------------------------------------------------------+"
+  echo "|          *** Installing 1Password  ***                   |"
+  echo "+----------------------------------------------------------+"
+
+  if command -v op > /dev/null; then
+    echo -e "\033[1;32m✔️  [SKIP] O 1Password já está disponível nada a ser feito aqui.\033[0m"
+    return
+  fi
+
+  if [ $PLATFORM_OS = "Fedora" ]; then
+    sudo rpm --import https://downloads.1password.com/linux/keys/1password.asc
+    sudo sh -c 'echo -e "[1password]\nname=1Password Stable Channel\nbaseurl=https://downloads.1password.com/linux/rpm/stable/\$basearch\nenabled=1\ngpgcheck=1\nrepo_gpgcheck=1\ngpgkey=\"https://downloads.1password.com/linux/keys/1password.asc\"" > /etc/yum.repos.d/1password.repo'
+    sudo dnf install 1password
+  elif [ $PLATFORM_OS = "Ubuntu" ]; then
+
+    if [ ! -f /usr/share/keyrings/1password-archive-keyring.gpg ]; then
+      curl -sS https://downloads.1password.com/linux/keys/1password.asc | sudo gpg --dearmor --output /usr/share/keyrings/1password-archive-keyring.gpg
+      echo 'deb [arch=amd64 signed-by=/usr/share/keyrings/1password-archive-keyring.gpg] https://downloads.1password.com/linux/debian/amd64 stable main' | sudo tee /etc/apt/sources.list.d/1password.list
+    fi
+    
+    [ ! -d /etc/debsig/policies/AC2D62742012EA22/ ] && sudo mkdir -p /etc/debsig/policies/AC2D62742012EA22/
+    if [ ! -f /etc/debsig/policies/AC2D62742012EA22/1password.pol ]; then
+      curl -sS https://downloads.1password.com/linux/debian/debsig/1password.pol | sudo tee /etc/debsig/policies/AC2D62742012EA22/1password.pol
+    fi
+
+    [ ! -d /usr/share/debsig/keyrings/AC2D62742012EA22 ] && sudo mkdir -p /usr/share/debsig/keyrings/AC2D62742012EA22
+    if [ ! -f /usr/share/debsig/keyrings/AC2D62742012EA22/debsig.gpg ]; then 
+      curl -sS https://downloads.1password.com/linux/keys/1password.asc | sudo gpg --dearmor --output /usr/share/debsig/keyrings/AC2D62742012EA22/debsig.gpg
+    fi
+    sudo apt update -qq && sudo apt install -qq -y 1password
+
+    if command -v op > /dev/null; then
+      # Mensagem de sucesso em verde com ícone de sucesso
+      echo -e "\033[1;32m✔️  [SUCESSO] O 1Password está disponível \033[0m"
+    else
+      # Mensagem de erro em vermelho com ícone de erro e recomendação de URL
+      echo -e "\033[1;31m❌  [ERRO] O 1Password não foi instalado! \033[0m"
+      echo -e "\033[1;31mPor favor, visite: https://support.1password.com/install-linux/#debian-or-ubuntu para instruções de instalação.\033[0m"
+    fi
+  elif [ $PLATFORM_OS = "MacOS" ]; then
+    echo "Install 1Password vai App Store" 
+  else
+    echo "Unsupported platorm"
+  fi
+  echo "\n\n\n"
+}
+
 
 ### Install base libs
 function install_base_packages() {
+  echo "+----------------------------------------------------------+"
+  echo "|    *** Installing basic package for O.S platform ***     |"
+  echo "+----------------------------------------------------------+"
+  echo " === PLATFORM_ARCH=$PLATFORM_ARCH; OS=$PLATFORM_OS ==="
+ 
   if [ ! -d $HOME/.local/bin ]; then
     echo "[BASH] Creating .local/bin ..."
     mkdir -p $HOME/.local/bin
   fi
 
   if [ $PLATFORM_OS = "Fedora" ]; then
-    sudo dnf upgrade -y 
+    sudo dnf upgrade -q -y 
     sudo dnf groupinstall @development-tools @development-libraries
     sudo dnf install @development-tools
     # Enable repo to LazyGit
     sudo dnf copr enable atim/lazygit -y
-    sudo dnf install -y \
+    sudo dnf install -q -y \
       automake \
       curl \
       gcc \
@@ -67,13 +122,11 @@ function install_base_packages() {
       fd-find \
       lazygit \
       jq
+    
 
-    sudo rpm --import https://downloads.1password.com/linux/keys/1password.asc
-    sudo sh -c 'echo -e "[1password]\nname=1Password Stable Channel\nbaseurl=https://downloads.1password.com/linux/rpm/stable/\$basearch\nenabled=1\ngpgcheck=1\nrepo_gpgcheck=1\ngpgkey=\"https://downloads.1password.com/linux/keys/1password.asc\"" > /etc/yum.repos.d/1password.repo'
-    sudo dnf install 1password
   elif [ $PLATFORM_OS = "Ubuntu" ]; then
-    sudo apt upgrade -y
-    sudo apt install -y build-essential \
+    sudo apt upgrade -qq -y
+    sudo apt install -qq -y build-essential \
       apt-transport-https \
       curl \
       git \
@@ -92,35 +145,32 @@ function install_base_packages() {
       fd-find \
       jq
     
-    LAZYGIT_VERSION=$(curl -s "https://api.github.com/repos/jesseduffield/lazygit/releases/latest" | grep -Po '"tag_name": "v\K[^"]*')
-    curl -Lo lazygit.tar.gz "https://github.com/jesseduffield/lazygit/releases/latest/download/lazygit_${LAZYGIT_VERSION}_Linux_x86_64.tar.gz"
-    tar xf lazygit.tar.gz lazygit
-    sudo install lazygit /usr/local/bin
 
-    echo "[INFO] 1Password playbook..."
-    curl -sS https://downloads.1password.com/linux/keys/1password.asc | sudo gpg --dearmor --output /usr/share/keyrings/1password-archive-keyring.gpg
-    echo 'deb [arch=amd64 signed-by=/usr/share/keyrings/1password-archive-keyring.gpg] https://downloads.1password.com/linux/debian/amd64 stable main' | sudo tee /etc/apt/sources.list.d/1password.list
-    sudo mkdir -p /etc/debsig/policies/AC2D62742012EA22/
-    curl -sS https://downloads.1password.com/linux/debian/debsig/1password.pol | sudo tee /etc/debsig/policies/AC2D62742012EA22/1password.pol
-    sudo mkdir -p /usr/share/debsig/keyrings/AC2D62742012EA22
-    curl -sS https://downloads.1password.com/linux/keys/1password.asc | sudo gpg --dearmor --output /usr/share/debsig/keyrings/AC2D62742012EA22/debsig.gpg
-    sudo apt update && sudo apt install 1password
+    if ! command -v op > /dev/null; then
+      echo -e "\033[1;33m⚠️  Atenção: O Ubuntu não possui uma versão do LazyGit disponível nos repositórios APT.\033[0m"
+      echo -e "\033[1;33mVamos precisará instalar o LazyGit manualmente via script.\033[0m"
+      echo -e "\033[1;33mPara isso, se esse script não conseguir fazer essa instalação siga as instruções no repositório oficial.\033[0m"
 
-    if command -v op > /dev/null; then
-      echo "[INFO] 1Password installed with success"
-    else
-      echo "[ERROR] The 1Password hasn't installed!"
+      LAZYGIT_VERSION=$(curl -s "https://api.github.com/repos/jesseduffield/lazygit/releases/latest" | grep -Po '"tag_name": "v\K[^"]*')
+      curl -Lo lazygit.tar.gz "https://github.com/jesseduffield/lazygit/releases/latest/download/lazygit_${LAZYGIT_VERSION}_Linux_x86_64.tar.gz"
+      tar xf lazygit.tar.gz lazygit
+      sudo install lazygit /usr/local/bin      
     fi
   elif [ $PLATFORM_OS = "MacOS" ]; then
     brew upgrade -y
     brew install zsh coreutils curl git wget tmux neovim ripgrep fd lazygit jq
   else
-    echo "Unsupported platorm"
+    echo -e "\033[1;31m❌  [ERRO] Unsupported platorm. \033[0m"
+    return
   fi
+
+  echo -e "\033[1;32m✔️  [SUCESSO] O basic packages for $PLATFORM_OS has been installed \033[0m\n\n\n"
 }
 
 function config_git() {
-  echo "[GIT] Configuring git..."
+  echo "+----------------------------------------------------------+"
+  echo "|             *** Configuring GIT SCM  ***                 |"
+  echo "+----------------------------------------------------------+"
 
   if [ ! -L $HOME/.gitconfig ]; then
     echo "[*] Copy .gitconfig"
@@ -132,9 +182,14 @@ function config_git() {
     echo "[*] Copy .gitignore_global"
     ln -s $DOTFILES_HOME/gitignore_global $HOME/.gitignore_global
   fi
+  echo -e "\033[1;32m✔️  [SUCESSO] GIT configured \033[0m\n\n\n"
 }
 
 function ensure_tmux_installed() {
+  echo "+----------------------------------------------------------+"
+  echo "|              *** Configuring TMUX  ***                   |"
+  echo "+----------------------------------------------------------+"
+
   # Ensure tmux installed
   if ! command -v tmux &> /dev/null 
   then 
@@ -164,15 +219,29 @@ function ensure_tmux_installed() {
   fi
   
 
+  if [ !  -d $XDG_CONFIG_HOME/tmux/ ];then 
+    echo "- Creates tmux config dir at $XDG_CONFIG_HOME/tmux/" 
+    mkdir -p $XDG_CONFIG_HOME/tmux/
+  fi 
+
   if [ ! -L $XDG_CONFIG_HOME/tmux/tmux.conf ]; then
+    echo "- Linking .tmux.conf "
     ln -s $DOTFILES_HOME/tmux/tmux.conf $XDG_CONFIG_HOME/tmux/tmux.conf
   fi
+
+  # if [ ! -L $HOME/.tmux.conf ]; then
+  #   ln -s $DOTFILES_HOME/tmux/tmux.conf $HOME/.tmux.conf
+  # fi
+  echo -e "\033[1;32m✔️  [SUCESSO] TMUX configued \033[0m\n\n"
 }
 
 
 
 function ensure_zplug_installed() {
   # Ensure zplug has been installed
+  echo "+----------------------------------------------------------+"
+  echo "|           *** Ensure zplug instaleld  ***                |"
+  echo "+----------------------------------------------------------+"
   if [ ! -d $XDG_CONFIG_HOME/zsh/plugins/zplug ]; then
     echo "[ZSH] Install zplug - Zsh Plugin Manager"
     git clone https://github.com/zplug/zplug $XDG_CONFIG_HOME/zsh/plugins/zplug
@@ -180,17 +249,55 @@ function ensure_zplug_installed() {
     zplug install
   else
     echo "[ZSH] zplug - Zsh Plugin Manager Alrady configured run '$ zplug install'"
+    echo -e "\033[1;32m✔️  [SUCESSO] Zsh Plugin Manager Alrady configured run '$ zplug install' \033[0m\n\n"
   fi
 }
 
 function ensure_asdf_installed() {
-  # Ensure asdf installed
-  echo "[ASDF] Install asdf-vm ..."
-  export ASDF_HOME=$XDG_CONFIG_HOME/asdf
+  echo "+----------------------------------------------------------+"
+  echo "|             *** Configuring ASDF-VM  ***                 |"
+  echo "+----------------------------------------------------------+"
+  export ASDF_HOME=$XDG_CONFIG_HOME/asdf/
   export ASDF_DIR=$ASDF_HOME
-  if [ ! -d $ASDF_HOME/ ]; then
-    echo "[*] Clonning repo"
-    git clone https://github.com/asdf-vm/asdf.git $ASDF_HOME
+  export ASDF_TARGET_VERSION="v0.16.2"
+  platform_lower=$(echo $PLATFORM_ARCH | tr '[:upper:]' '[:lower:]')
+
+  # Converter MACHINE_ARCH para o formato correto
+  if [ "$MACHINE_ARCH" == "ARM_64" ]; then
+    machine_arch="arm64"
+  elif [ "$MACHINE_ARCH" == "AMD_64" || "$MACHINE_ARCH" == "x86_64" ]; then
+    machine_arch="amd64"
+  else
+    #machine_arch=$(echo $MACHINE_ARCH | tr '[:upper:]' '[:lower:]')
+    machine_arch="amd64"
+  fi
+  asdf_bin_ver="asdf-${ASDF_TARGET_VERSION}-${platform_lower}-${machine_arch}.tar.gz"
+
+  if ! command -v asdf > /dev/null ; then
+    echo "- Download asdf Release $ASDF_TARGET_VERSION ($asdf_bin_ver)"
+    echo "\t clonning from https://github.com/asdf-vm/asdf/releases/download/$ASDF_TARGET_VERSION/$asdf_bin_ver"
+
+    curl -L https://github.com/asdf-vm/asdf/releases/download/$ASDF_TARGET_VERSION/$asdf_bin_ver -o /tmp/$asdf_bin_ver
+
+    if [ $? -eq 0 ]; then
+      echo "- Download successful, extracting the archive"
+
+      tar -xvzf /tmp/$asdf_bin_ver -C $HOME/.local/bin
+
+      if [ -f $HOME/.local/bin/asdf ]; then
+        echo "- asdf binary installed successfully at $HOME/.local/bin/asdf"
+        
+        if command -v asdf > /dev/null; then
+          echo "- asdf is available for zsh"
+        else
+          echo "- asdf is not available in zsh. Ensure $HOME/.local/bin is in your PATH."
+        fi
+      else
+        echo "- Error: asdf binary extraction failed!"
+      fi
+    else
+      echo "- Error: Failed to download $asdf_bin_ver"
+    fi
   else
     echo "[ ] Clonning repo (SKIPPED)"
   fi
@@ -233,14 +340,17 @@ function ensure_asdf_installed() {
 function ensure_neovim() {
   export NEOVIM_CONF_HOME=$XDG_CONFIG_HOME/nvim
 
-  echo "[EDITOR] Install or config neovim ..."
+  echo "+----------------------------------------------------------+"
+  echo "|          *** Install and config neovim  ***              |"
+  echo "+----------------------------------------------------------+"
+
   if ! command -v nvim > /dev/null; then
-    echo "[x] Install neovim (not supported)"
+    echo "❌ Install neovim (not supported), please install manual"
   fi
 
   if ! command -v lua > /dev/null; then
-    echo "[x] Please install LUA"
-    echo "  run: 'asdf install lua latest && asdf global lua latest'"
+    echo "❌ Please install LUA"
+    echo "    run: 'asdf plugin add lua && asdf plugin add lua-language-server && asdf install lua latest && asdf global lua latest'"
   fi
 
   if [ ! -L $NEOVIM_CONF_HOME/init.lua ]; then
@@ -252,10 +362,12 @@ function ensure_neovim() {
     echo "[*] creates symlink to lua config folder"
     ln -s $DOTFILES_HOME/nvim/lua/ $NEOVIM_CONF_HOME/lua
   fi
-
 }
+
 install_base_packages
+ensure_1p
 config_git
 ensure_zplug_installed
 ensure_asdf_installed
+ensure_tmux_installed
 ensure_neovim
